### ISSUE TITLE
Issue when reentering the page

### ISSUE THREAD

**Issue by nevakee716** [nevakee716/ReverseList#2]
Hey Guys, I was hoping you could help me out real quick. I am trying to use the reverse list layout and at first glance it is working great. But it seems that it is only working the first time I hit the page.
 
Let me know if you have any thoughts. Thanks - Tony
 
The list is on an object page and looks like this the first time it loads, which is correct.

 
Once I navigate away from the page, then return, the structure goes away and it doesn't work

**Comment by JGrndn** [comment]
Fix with version 1.1.1
